.TH "md__r_e_a_d_m_e" 3 "Wed Feb 1 2023" "Zaliczenie165433" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__r_e_a_d_m_e \- stolarz_kamil_test 
.PP

.SH "Projekt jest egzaminem realizowanym w ramach zajęć\&."
.PP
.SS "W ramach zaliczenia:"
.IP "\(bu" 2
stworzono repozytorium
.IP "\(bu" 2
napisano klasy cpp
.IP "\(bu" 2
dodano dokumentacje w formacie Doxygen 
.PP

