.TH "Statistic.h" 3 "Wed Feb 1 2023" "Zaliczenie165433" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Statistic.h \- Plik nagłówkowy klasy \fBStatistic\fP\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBStatistic\fP"
.br
.RI "Reprezentuje rozkład normalny z średnią i odchyleniem standardowym\&. "
.in -1c
.SH "Detailed Description"
.PP 
Plik nagłówkowy klasy \fBStatistic\fP\&. 

Plik zawiera definicję klasy \fBStatistic\fP, która służy do obliczania rozkładu normalnego\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Zaliczenie165433 from the source code\&.
